### ISSUE TITLE
OrderType, SignalType enums are not copyable

### ISSUE THREAD

**Issue by NirAbramovich** [ryanpig/finviz-rs#2]
For example, when writing this piece of code:
```
pub struct FinvizHelper{
    signal: SignalType,
    order: OrderType,
}

impl FinvizHelper{
    pub async fn get(&self) -> Result<(),Box<dyn std::error::Error>> {
        Screener::new(ScreenerType::Overview)
            .set_signal(self.signal)
            .set_order(self.order)
            .scrape().await?
            .to_csv_file("output.csv")?;
        Ok(())
    }
}
```

The members `self.signal` and `self.order` are not copyable because their matching types are not copyable, therefore there's implicit move, but the required behavior here is copy.

Solution:
change current `#derive` of `SignalType`, `OrderType` to `#[derive(Copy, EnumIter)]`

**Comment by ryanpig** [comment]
I've added both `Copy` and `Clone` for most of enum types except for `InsiderType`, which has `Numeric(String)` field that doesn't implement `Copy`.
